logo: /img/aryan-1.jpeg
description: I have always been intrigued by the power of data and how it can help us make informed decisions and drive meaningful insights, which led me to pursue a career in Data Science.
#show_downloads: true
theme: jekyll-theme-minimal